name: CI Tests
on:
  pull_request:
    branches:
      - 'deployment-test-branch'
    paths:
      - 'best-practices/code/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: 'best-practices/code'
        run: pip install pipenv && pipenv install --dev

      - name: Run Unit tests
        working-directory: "best-practices/code"
        run: pipenv run pytest tests/